# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-mavenname: Build/publish Docker image & update image version in config

on:
  release:
    types: [created]

jobs:
  call-workflow-maven-build:
    uses: felleslosninger/eid-github-workflows/.github/workflows/maven-release-lib.yml@main
    with:
      java-version: 17
    secrets:
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}
      packages-user: ${{ secrets.CREATE_PACKAGES_USER }}
      packages-token: ${{ secrets.CREATE_PACKAGES_TOKEN }}
